version: '3.7'

services:
  ruby:
    container_name: api
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api:/api
    ports:
      - "4000:3000"
  front:
    container_name: front
    image: node:lts-alpine
    working_dir: /front
    volumes:
      - ./front:/front
    ports:
      - "4001:3000"
    command: /bin/sh -c "[ -d node_modules ] && echo "up-to-date" || yarn && yarn start"
